name: consumo_api_store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-205.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3  
  flutter_bloc: ^8.0.1 
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
